<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="6" ignored="0" total="14" passed="5" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-11-12T13:44:18 IST" name="FreeCRM application test" finished-at="2021-11-12T13:46:26 IST" duration-ms="127855">
    <groups>
    </groups>
    <test started-at="2021-11-12T13:44:18 IST" name="End to End testing" finished-at="2021-11-12T13:46:26 IST" duration-ms="127855">
      <class name="com.crm.qa.tests.LoginPageTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.crm.qa.tests.LoginPageTest@30865a90]" started-at="2021-11-12T13:44:18 IST" name="setup" finished-at="2021-11-12T13:44:31 IST" duration-ms="12811" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="loginPageTitleTest()[pri:0, instance:com.crm.qa.tests.LoginPageTest@30865a90]" started-at="2021-11-12T13:44:31 IST" name="loginPageTitleTest" finished-at="2021-11-12T13:44:31 IST" duration-ms="38" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginPageTitleTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.crm.qa.tests.LoginPageTest@30865a90]" started-at="2021-11-12T13:44:31 IST" name="tearDown" finished-at="2021-11-12T13:44:31 IST" duration-ms="179" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.crm.qa.tests.LoginPageTest@30865a90]" started-at="2021-11-12T13:44:31 IST" name="setup" finished-at="2021-11-12T13:44:41 IST" duration-ms="9894" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="loginPageLogoTest()[pri:1, instance:com.crm.qa.tests.LoginPageTest@30865a90]" started-at="2021-11-12T13:44:41 IST" name="loginPageLogoTest" finished-at="2021-11-12T13:44:41 IST" duration-ms="106" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginPageLogoTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.crm.qa.tests.LoginPageTest@30865a90]" started-at="2021-11-12T13:44:41 IST" name="tearDown" finished-at="2021-11-12T13:44:41 IST" duration-ms="181" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.crm.qa.tests.LoginPageTest@30865a90]" started-at="2021-11-12T13:44:41 IST" name="setup" finished-at="2021-11-12T13:44:48 IST" duration-ms="6633" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="loginPageLoginTest()[pri:2, instance:com.crm.qa.tests.LoginPageTest@30865a90]" started-at="2021-11-12T13:44:48 IST" name="loginPageLoginTest" finished-at="2021-11-12T13:44:54 IST" duration-ms="6277" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginPageLoginTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.crm.qa.tests.LoginPageTest@30865a90]" started-at="2021-11-12T13:44:54 IST" name="tearDown" finished-at="2021-11-12T13:44:55 IST" duration-ms="173" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.crm.qa.tests.LoginPageTest -->
      <class name="com.crm.qa.tests.HomePageTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.crm.qa.tests.HomePageTest@75201592]" started-at="2021-11-12T13:44:18 IST" name="setup" finished-at="2021-11-12T13:44:50 IST" duration-ms="32012" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.crm.qa.tests.HomePageTest@75201592]" started-at="2021-11-12T13:44:18 IST" name="setup" finished-at="2021-11-12T13:44:35 IST" duration-ms="17252" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyHomePageTitle()[pri:0, instance:com.crm.qa.tests.HomePageTest@75201592]" started-at="2021-11-12T13:44:35 IST" name="verifyHomePageTitle" finished-at="2021-11-12T13:44:35 IST" duration-ms="11" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyHomePageTitle -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.crm.qa.tests.HomePageTest@75201592]" started-at="2021-11-12T13:44:36 IST" name="tearDown" finished-at="2021-11-12T13:44:36 IST" duration-ms="53" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method retried="true" signature="clickOnContactsLink()[pri:1, instance:com.crm.qa.tests.HomePageTest@75201592]" started-at="2021-11-12T13:44:50 IST" name="clickOnContactsLink" finished-at="2021-11-12T13:44:52 IST" duration-ms="2204" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.crm.qa.tests.HomePageTest.clickOnContactsLink(HomePageTest.java:58)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clickOnContactsLink -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.crm.qa.tests.HomePageTest@75201592]" started-at="2021-11-12T13:44:52 IST" name="tearDown" finished-at="2021-11-12T13:44:53 IST" duration-ms="59" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.crm.qa.tests.HomePageTest@75201592]" started-at="2021-11-12T13:44:53 IST" name="setup" finished-at="2021-11-12T13:45:05 IST" duration-ms="12016" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method retried="true" signature="clickOnContactsLink()[pri:1, instance:com.crm.qa.tests.HomePageTest@75201592]" started-at="2021-11-12T13:45:05 IST" name="clickOnContactsLink" finished-at="2021-11-12T13:45:06 IST" duration-ms="1459" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.crm.qa.tests.HomePageTest.clickOnContactsLink(HomePageTest.java:58)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clickOnContactsLink -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.crm.qa.tests.HomePageTest@75201592]" started-at="2021-11-12T13:45:06 IST" name="tearDown" finished-at="2021-11-12T13:45:06 IST" duration-ms="48" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.crm.qa.tests.HomePageTest@75201592]" started-at="2021-11-12T13:45:06 IST" name="setup" finished-at="2021-11-12T13:45:23 IST" duration-ms="17427" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="clickOnContactsLink()[pri:1, instance:com.crm.qa.tests.HomePageTest@75201592]" started-at="2021-11-12T13:45:23 IST" name="clickOnContactsLink" finished-at="2021-11-12T13:45:25 IST" duration-ms="1726" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.crm.qa.tests.HomePageTest.clickOnContactsLink(HomePageTest.java:58)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clickOnContactsLink -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.crm.qa.tests.HomePageTest@75201592]" started-at="2021-11-12T13:45:26 IST" name="tearDown" finished-at="2021-11-12T13:45:26 IST" duration-ms="70" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.crm.qa.tests.HomePageTest -->
      <class name="com.crm.qa.tests.ContactsPageTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.crm.qa.tests.ContactsPageTest@6c2d4cc6]" started-at="2021-11-12T13:44:18 IST" name="setup" finished-at="2021-11-12T13:44:44 IST" duration-ms="26218" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.crm.qa.tests.ContactsPageTest@6c2d4cc6]" started-at="2021-11-12T13:44:37 IST" name="setup" finished-at="2021-11-12T13:44:53 IST" duration-ms="16198" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifySelectContactsByName()[pri:0, instance:com.crm.qa.tests.ContactsPageTest@6c2d4cc6]" started-at="2021-11-12T13:44:44 IST" name="verifySelectContactsByName" finished-at="2021-11-12T13:44:45 IST" duration-ms="163" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySelectContactsByName -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.crm.qa.tests.ContactsPageTest@6c2d4cc6]" started-at="2021-11-12T13:44:45 IST" name="tearDown" finished-at="2021-11-12T13:44:45 IST" duration-ms="383" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method retried="true" signature="verifyCreateNewContact(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:1, instance:com.crm.qa.tests.ContactsPageTest@6c2d4cc6]" started-at="2021-11-12T13:44:53 IST" name="verifyCreateNewContact" data-provider="CRMfile" finished-at="2021-11-12T13:44:55 IST" duration-ms="2672" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[Mr.]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Rakesh]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Nayak]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[FCC]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.crm.qa.tests.ContactsPageTest.verifyCreateNewContact(ContactsPageTest.java:59)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyCreateNewContact -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.crm.qa.tests.ContactsPageTest@6c2d4cc6]" started-at="2021-11-12T13:44:55 IST" name="tearDown" finished-at="2021-11-12T13:44:56 IST" duration-ms="127" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.crm.qa.tests.ContactsPageTest@6c2d4cc6]" started-at="2021-11-12T13:44:56 IST" name="setup" finished-at="2021-11-12T13:45:09 IST" duration-ms="13749" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method retried="true" signature="verifyCreateNewContact(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:1, instance:com.crm.qa.tests.ContactsPageTest@6c2d4cc6]" started-at="2021-11-12T13:45:09 IST" name="verifyCreateNewContact" data-provider="CRMfile" finished-at="2021-11-12T13:45:12 IST" duration-ms="2332" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[Mr.]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Rakesh]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Nayak]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[FCC]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.crm.qa.tests.ContactsPageTest.verifyCreateNewContact(ContactsPageTest.java:59)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyCreateNewContact -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.crm.qa.tests.ContactsPageTest@6c2d4cc6]" started-at="2021-11-12T13:45:12 IST" name="tearDown" finished-at="2021-11-12T13:45:12 IST" duration-ms="121" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.crm.qa.tests.ContactsPageTest@6c2d4cc6]" started-at="2021-11-12T13:45:12 IST" name="setup" finished-at="2021-11-12T13:45:27 IST" duration-ms="15047" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyCreateNewContact(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:1, instance:com.crm.qa.tests.ContactsPageTest@6c2d4cc6]" started-at="2021-11-12T13:45:27 IST" name="verifyCreateNewContact" data-provider="CRMfile" finished-at="2021-11-12T13:45:29 IST" duration-ms="2040" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Mr.]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Rakesh]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Nayak]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[FCC]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.crm.qa.tests.ContactsPageTest.verifyCreateNewContact(ContactsPageTest.java:59)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyCreateNewContact -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.crm.qa.tests.ContactsPageTest@6c2d4cc6]" started-at="2021-11-12T13:45:29 IST" name="tearDown" finished-at="2021-11-12T13:45:29 IST" duration-ms="124" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.crm.qa.tests.ContactsPageTest@6c2d4cc6]" started-at="2021-11-12T13:45:29 IST" name="setup" finished-at="2021-11-12T13:45:47 IST" duration-ms="18142" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method retried="true" signature="verifyCreateNewContact(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:1, instance:com.crm.qa.tests.ContactsPageTest@6c2d4cc6]" started-at="2021-11-12T13:45:47 IST" name="verifyCreateNewContact" data-provider="CRMfile" finished-at="2021-11-12T13:45:50 IST" duration-ms="2242" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[Dr.]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Nick]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[John]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[BOO]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.crm.qa.tests.ContactsPageTest.verifyCreateNewContact(ContactsPageTest.java:59)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyCreateNewContact -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.crm.qa.tests.ContactsPageTest@6c2d4cc6]" started-at="2021-11-12T13:45:50 IST" name="tearDown" finished-at="2021-11-12T13:45:50 IST" duration-ms="116" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.crm.qa.tests.ContactsPageTest@6c2d4cc6]" started-at="2021-11-12T13:45:50 IST" name="setup" finished-at="2021-11-12T13:46:06 IST" duration-ms="16590" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method retried="true" signature="verifyCreateNewContact(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:1, instance:com.crm.qa.tests.ContactsPageTest@6c2d4cc6]" started-at="2021-11-12T13:46:06 IST" name="verifyCreateNewContact" data-provider="CRMfile" finished-at="2021-11-12T13:46:08 IST" duration-ms="1868" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[Dr.]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Nick]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[John]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[BOO]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.crm.qa.tests.ContactsPageTest.verifyCreateNewContact(ContactsPageTest.java:59)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyCreateNewContact -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.crm.qa.tests.ContactsPageTest@6c2d4cc6]" started-at="2021-11-12T13:46:08 IST" name="tearDown" finished-at="2021-11-12T13:46:08 IST" duration-ms="125" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.crm.qa.tests.ContactsPageTest@6c2d4cc6]" started-at="2021-11-12T13:46:08 IST" name="setup" finished-at="2021-11-12T13:46:23 IST" duration-ms="14704" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyCreateNewContact(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:1, instance:com.crm.qa.tests.ContactsPageTest@6c2d4cc6]" started-at="2021-11-12T13:46:23 IST" name="verifyCreateNewContact" data-provider="CRMfile" finished-at="2021-11-12T13:46:25 IST" duration-ms="2237" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Dr.]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Nick]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[John]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[BOO]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.crm.qa.tests.ContactsPageTest.verifyCreateNewContact(ContactsPageTest.java:59)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyCreateNewContact -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.crm.qa.tests.ContactsPageTest@6c2d4cc6]" started-at="2021-11-12T13:46:26 IST" name="tearDown" finished-at="2021-11-12T13:46:26 IST" duration-ms="150" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.crm.qa.tests.ContactsPageTest -->
    </test> <!-- End to End testing -->
  </suite> <!-- FreeCRM application test -->
</testng-results>
